/*
 * Copyright © 2008  Red Hat, Inc. All rights reserved.
 * Copyright © 2008  Ding-Yi Chen <dchen at redhat dot com>
 *
 * This file is part of the libUnihan Project.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */ 
#include <stdio.h>
#include <stdlib.h>
#include "Unihan.h"
#include "Unihan_phonetic.h"
#include "Unihan_phonetic_tables.h"


const char *PINYIN_COMBINATION_TABLES_ALWAYS[]={
    "BA",
    "BO",
    "BAI",
    "BEI",
    "BAO",
    "BAN",
    "BEN",
    "BANG",
    "BENG",
    "BI",
    "BIÊ",
    "BIAO",
    "BIAN",
    "BIN",
    "BING",
    "BU",
    "PA",
    "PO",
    "PAI",
    "PEI",
    "PAO",
    "POU",
    "PAN",
    "PEN",
    "PANG",
    "PENG",
    "PI",
    "PIÊ",
    "PIAO",
    "PIAN",
    "PIN",
    "PING",
    "PU",
    "MA",
    "MO",
    "ME",
    "MAI",
    "MEI",
    "MAO",
    "MOU",
    "MAN",
    "MEN",
    "MANG",
    "MENG",
    "MI",
    "MIÊ",
    "MIAO",
    "MIU",
    "MIAN",
    "MIN",
    "MING",
    "MU",
    "FA",
    "FO",
    "FEI",
    "FOU",
    "FAN",
    "FEN",
    "FANG",
    "FENG",
    "FIAO",
    "FU",
    "FONG",
    "DA",
    "DE",
    "DAI",
    "DEI",
    "DAO",
    "DOU",
    "DAN",
    "DEN",
    "DANG",
    "DENG",
    "DI",
    "DIA",
    "DIÊ",
    "DIAO",
    "DIU",
    "DIAN",
    "DANG",
    "DING",
    "DU",
    "DUO",
    "DUI",
    "DUAN",
    "DUN",
    "DONG",
    "TA",
    "TE",
    "TAI",
    "TAO",
    "TOU",
    "TAN",
    "TANG",
    "TENG",
    "TI",
    "TIÊ",
    "TIAO",
    "TIAN",
    "TING",
    "TU",
    "TUO",
    "TUI",
    "TUAN",
    "TUN",
    "TONG",
    "NA",
    "NE",
    "NAI",
    "NEI",
    "NAO",
    "NOU",
    "NAN",
    "NEN",
    "NANG",
    "NENG",
    "NI",
    "NIA",
    "NIÊ",
    "NIAO",
    "NIU",
    "NIAN",
    "NIN",
    "NIANG",
    "NING",
    "NU",
    "NUO",
    "NUAN",
    "NUN",
    "NONG",
    "NÜ",
    "NÜÊ",
    "LA",
    "LO",
    "LE",
    "LAI",
    "LEI",
    "LAO",
    "LOU",
    "LAN",
    "LANG",
    "LENG",
    "LI",
    "LIA",
    "LIÊ",
    "LIAO",
    "LIU",
    "LIAN",
    "LEN",
    "LIANG",
    "LENG",
    "LU",
    "LUO",
    "LUAN",
    "LUN",
    "LONG",
    "LÜ",
    "LÜÊ",
    "LÜAN",
    "GA",
    "GE",
    "GAI",
    "GEI",
    "GAO",
    "GOU",
    "GAN",
    "GEN",
    "GANG",
    "GENG",
    "GU",
    "GUA",
    "GUO",
    "GUAI",
    "GUI",
    "GUAN",
    "GUN",
    "GUANG",
    "GONG",
    "KA",
    "KE",
    "KAI",
    "KAO",
    "KOU",
    "KAN",
    "KEN",
    "KANG",
    "KENG",
    "KU",
    "KUA",
    "KUO",
    "KUAI",
    "KUI",
    "KUAN",
    "KUN",
    "KUANG",
    "KONG",
    "HA",
    "HE",
    "HAI",
    "HEI",
    "HAO",
    "HOU",
    "HAN",
    "HEN",
    "HANG",
    "HENG",
    "HU",
    "HUA",
    "HUO",
    "HUAI",
    "HUI",
    "HUAN",
    "HUN",
    "HUANG",
    "HONG",
    "JI",
    "JIA",
    "JIÊ",
    "JIAO",
    "JIU",
    "JIAN",
    "JEN",
    "JIANG",
    "JENG",
    "JÜ",
    "JÜÊ",
    "JÜAN",
    "JÜN",
    "JIONG",
    "QI",
    "QIA",
    "QIÊ",
    "QIAO",
    "QIU",
    "QIAN",
    "QEN",
    "QIANG",
    "QENG",
    "QÜ",
    "QÜÊ",
    "QÜAN",
    "QÜN",
    "QIONG",
    "XI",
    "XIA",
    "XIÊ",
    "XIAO",
    "XIU",
    "XIAN",
    "XEN",
    "XIANG",
    "XENG",
    "XÜ",
    "XÜÊ",
    "XÜAN",
    "XÜN",
    "XIONG",
    "ZHI",
    "ZHA",
    "ZHE",
    "ZHAI",
    "ZHEI",
    "ZHAO",
    "ZHOU",
    "ZHAN",
    "ZHEN",
    "ZHANG",
    "ZHENG",
    "ZHU",
    "ZHUA",
    "ZHUO",
    "ZHUAI",
    "ZHUI",
    "ZHUAN",
    "ZHUN",
    "ZHUANG",
    "ZHONG",
    "CHI",
    "CHA",
    "CHE",
    "CHAI",
    "CHAO",
    "CHOU",
    "CHAN",
    "CHEN",
    "CHANG",
    "CHENG",
    "CHU",
    "CHUA",
    "CHUO",
    "CHUAI",
    "CHUI",
    "CHUAN",
    "CHUN",
    "CHUANG",
    "CHONG",
    "SHI",
    "SHA",
    "SHE",
    "SHAI",
    "SHEI",
    "SHAO",
    "SHOU",
    "SHAN",
    "SHEN",
    "SHANG",
    "SHENG",
    "SHU",
    "SHUA",
    "SHUO",
    "SHUAI",
    "SHUI",
    "SHUAN",
    "SHUN",
    "SHUANG",
    "RI",
    "RE",
    "RAO",
    "ROU",
    "RAN",
    "REN",
    "RANG",
    "RENG",
    "RU",
    "RUO",
    "RUI",
    "RUAN",
    "RUN",
    "RONG",
    "ZI",
    "ZA",
    "ZE",
    "ZAI",
    "ZEI",
    "ZAO",
    "ZOU",
    "ZAN",
    "ZEN",
    "ZANG",
    "ZENG",
    "ZU",
    "ZUO",
    "ZUI",
    "ZUAN",
    "ZUN",
    "ZONG",
    "CI",
    "CA",
    "CE",
    "CAI",
    "CAO",
    "COU",
    "CAN",
    "CEN",
    "CANG",
    "CENG",
    "CU",
    "CUO",
    "CUI",
    "CUAN",
    "CUN",
    "CONG",
    "SI",
    "SA",
    "SE",
    "SAI",
    "SEI",
    "SAO",
    "SOU",
    "SAN",
    "SEN",
    "SANG",
    "SENG",
    "SU",
    "SUO",
    "SUI",
    "SUAN",
    "SUN",
    "SONG",
    "A",
    "O",
    "E",
    "Ê",
    "AI",
    "EI",
    "AO",
    "OU",
    "AN",
    "EN",
    "ANG",
    "ENG",
    "ER",
    "YI",
    "YA",
    "YO",
    "YE",
    "YAI",
    "YAO",
    "YÜ",
    "YAN",
    "YIN",
    "YANG",
    "YING",
    "WU",
    "WA",
    "WO",
    "WAI",
    "WI",
    "WAN",
    "WN",
    "WANG",
    "WENG",
    "YÜ",
    "YÜÊ",
    "YÜAN",
    "YÜN",
    "YONG",
    NULL
};

typedef enum{
    PINYIN_ALWAYS,
    PINYIN_ORIGINAL,
    ZHUYIN_ALWAYS,
    ZHUYIN_ORIGINAL
} TEST_ID;

#define TEST_NUM ZHUYIN_ORIGINAL +1

const char *test_msgs[]={
    "converting to pinyin ALWAYS",
    "converting to pinyin ORIGINAL",
    "converting to zhuyin ALWAYS",
    "converting to zhuyin ORIGINAL",
    NULL
};

const char **dataSet[]={
    PINYIN_COMBINATION_TABLES_ALWAYS,
    PINYIN_COMBINATION_TABLES,
    ZHUYIN_COMBINATION_TABLES,
    ZHUYIN_COMBINATION_TABLES,
};

gboolean perform_test(TEST_ID testId){
    const char **fromArray=NULL;
    const char **toArray=NULL;
    printf("Testing on %s \n",test_msgs[testId]);

    char *out;
    guint i,j;
    for(j=0;j<TEST_NUM;j++){
	printf(" Sub-test %d: ...",j);
	toArray=dataSet[testId];
	fromArray=dataSet[j];
	for(i=0;fromArray[i]!=NULL;i++){
	    if (j<ZHUYIN_ALWAYS){
		if (testId<ZHUYIN_ALWAYS){
		    out=pinYin_convert_accent_format(fromArray[i],testId,FALSE);
		}else{
		    out=pinYin_to_zhuYin(fromArray[i],testId-ZHUYIN_ALWAYS);
		}
	    }else{
		if (testId<ZHUYIN_ALWAYS){
		    out=zhuYin_to_pinYin(fromArray[i],testId,FALSE);
		}else{
		    out=zhuYin_convert_toneMark_format(fromArray[i],testId-ZHUYIN_ALWAYS);
		}
	    }
	    if (strcmp(out,toArray[i])!=0){
		printf(" Failed: Orig:%s Out:%s Exp:%s\n",fromArray[i],out,toArray[i]);
		return FALSE;
	    }
	}
	printf(" completed.\n");
    }
    printf("All sub-test completed.\n");
    return TRUE;
}

int main(int argc, char** argv){
    int test_index=atoi(argv[1]);
    if (perform_test(test_index)){
	printf("Success!");
	return 0;
    }
    return 1;

}
