# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dchen/devel/SourceForge/libUnihan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dchen/devel/SourceForge/libUnihan

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config /home/dchen/devel/SourceForge/libUnihan/CPackConfig.cmake

# Special rule for the target package
package/fast: package

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config /home/dchen/devel/SourceForge/libUnihan/CPackSourceConfig.cmake

# Special rule for the target package_source
package_source/fast: package_source

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dchen/devel/SourceForge/libUnihan/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dchen/devel/SourceForge/libUnihan/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named Unihan.db

# Build rule for target.
Unihan.db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Unihan.db

# fast build rule for target.
Unihan.db/fast:
	$(MAKE) -f CMakeFiles/Unihan.db.dir/build.make CMakeFiles/Unihan.db.dir/build

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f CMakeFiles/doxygen.dir/build.make CMakeFiles/doxygen.dir/build

#=============================================================================
# Target rules for targets named install_db

# Build rule for target.
install_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 install_db

# fast build rule for target.
install_db/fast:
	$(MAKE) -f CMakeFiles/install_db.dir/build.make CMakeFiles/install_db.dir/build

#=============================================================================
# Target rules for targets named package_db

# Build rule for target.
package_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 package_db

# fast build rule for target.
package_db/fast:
	$(MAKE) -f CMakeFiles/package_db.dir/build.make CMakeFiles/package_db.dir/build

#=============================================================================
# Target rules for targets named package_db_doc

# Build rule for target.
package_db_doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 package_db_doc

# fast build rule for target.
package_db_doc/fast:
	$(MAKE) -f CMakeFiles/package_db_doc.dir/build.make CMakeFiles/package_db_doc.dir/build

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build

#=============================================================================
# Target rules for targets named Unihan

# Build rule for target.
Unihan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Unihan

# fast build rule for target.
Unihan/fast:
	$(MAKE) -f bin/CMakeFiles/Unihan.dir/build.make bin/CMakeFiles/Unihan.dir/build

#=============================================================================
# Target rules for targets named unihan_converter

# Build rule for target.
unihan_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unihan_converter

# fast build rule for target.
unihan_converter/fast:
	$(MAKE) -f bin/CMakeFiles/unihan_converter.dir/build.make bin/CMakeFiles/unihan_converter.dir/build

#=============================================================================
# Target rules for targets named unihan_field_validation

# Build rule for target.
unihan_field_validation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unihan_field_validation

# fast build rule for target.
unihan_field_validation/fast:
	$(MAKE) -f bin/CMakeFiles/unihan_field_validation.dir/build.make bin/CMakeFiles/unihan_field_validation.dir/build

#=============================================================================
# Target rules for targets named unihan_query

# Build rule for target.
unihan_query: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unihan_query

# fast build rule for target.
unihan_query/fast:
	$(MAKE) -f bin/CMakeFiles/unihan_query.dir/build.make bin/CMakeFiles/unihan_query.dir/build

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Unihan.db"
	@echo "... doxygen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install_db"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_db"
	@echo "... package_db_doc"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... Unihan"
	@echo "... unihan_converter"
	@echo "... unihan_field_validation"
	@echo "... unihan_query"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

