/*
 * Copyright © 2008  Red Hat, Inc. All rights reserved.
 * Copyright © 2008  Ding-Yi Chen <dchen at redhat dot com>
 *
 * This file is part of the libUnihan Project.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA  02111-1307  USA
 */


/**
 * UNIHAN_FIELD_NAMES.
 *
 *
 */
const char *UNIHAN_FIELD_NAMES[UNIHAN_FIELDS_COUNT+1]={
    "code",
    "kAccountingNumeric",
    "kBigFive",
    "kCangjie",
    "kCantonese",
    "kCCCII",
    "kCheungBauer",
    "kCheungBauerIndex",
    "kCihaiT",
    "kCNS1986",
    "kCNS1992",
    "kCompatibilityVariant",
    "kCowles",
    "kDaeJaweon",
    "kDefinition",
    "kEACC",
    "kFenn",
    "kFennIndex",
    "kFourCornerCode",
    "kFrequency",
    "kGB0",
    "kGB1",
    "kGB3",
    "kGB5",
    "kGB7",
    "kGB8",
    "kGradeLevel",
    "kGSR",
    "kHangul",
    "kHanYu",
    "kHanyuPinlu",
    "kHDZRadBreak",
    "kHKGlyph",
    "kHKSCS",
    "kIBMJapan",
    "kIICore",
    "kIRGDaeJaweon",
    "kIRGDaiKanwaZiten",
    "kIRGHanyuDaZidian",
    "kIRGKangXi",
    "kIRG_GSource",
    "kIRG_HSource",
    "kIRG_JSource",
    "kIRG_KPSource",
    "kIRG_KSource",
    "kIRG_TSource",
    "kIRG_USource",
    "kIRG_VSource",
    "kJapaneseKun",
    "kJapaneseOn",
    "kJIS0213",
    "kJis0",
    "kJis1",
    "kKangXi",
    "kKarlgren",
    "kKorean",
    "kKPS0",
    "kKPS1",
    "kKSC0",
    "kKSC1",
    "kLau",
    "kMainlandTelegraph",
    "kMandarin",
    "kMatthews",
    "kMeyerWempe",
    "kMorohashi",
    "kNelson",
    "kOtherNumeric",
    "kPhonetic",
    "kPrimaryNumeric",
    "kPseudoGB1",
    "kRSAdobe_Japan1_6",
    "kRSJapanese",
    "kRSKangXi",
    "kRSKanWa",
    "kRSKorean",
    "kRSUnicode",
    "kSBGY",
    "kSemanticVariant",
    "kSimplifiedVariant",
    "kSpecializedSemanticVariant",
    "kTaiwanTelegraph",
    "kTang",
    "kTotalStrokes",
    "kTraditionalVariant",
    "kVietnamese",
    "kXerox",
    "kXHC1983",
    "kZVariant",

    "utf8",

    "IRG_source_short_name",

    "IRG_source_mapping",

    "variant_type",
    "variant_code",

    "from_dict",
    "semantic_T",
    "semantic_B",
    "semantic_Z",

    "radical_index",
    "additional_stroke_count",
    "radical_is_simplified",

    "adobeCID_CV",
    "adobeCID",
    "adobeCID_radicalStrokeCount",

    "KangXi_page",
    "KangXi_charNum",
    "KangXi_virtual",

    "freq_rank",

    "pinYin",
    "pinYin_base",
    "pinYin_tone",
    "pinYin_freq",

    "zVariant_source",

    "zhuYin",
    NULL
};

const char *UNIHAN_TABLE_NAMES[]={
    "kAccountingNumericTable",
    "kBigFiveTable",
    "kCangjieTable",
    "kCantoneseTable",
    "kCCCIITable",
    "kCheungBauerIndexTable",
    "kCheungBauerTable",
    "kCihaiTTable",
    "kCNS1986Table",
    "kCNS1992Table",
    "kCompatibilityVariantTable",
    "kCowlesTable",
    "kDaeJaweonTable",
    "kDefinitionTable",
    "kEACCTable",
    "kFennTable",
    "kFennIndexTable",
    "kFourCornerCodeTable",
    "kFrequencyTable",
    "kGB0Table",
    "kGB1Table",
    "kGB3Table",
    "kGB5Table",
    "kGB7Table",
    "kGB8Table",
    "kGradeLevelTable",
    "kGSRTable",
    "kHangulTable",
    "kHanYuTable",
    "kHanyuPinluTable",
    "kHDZRadBreakTable",
    "kHKGlyphTable",
    "kHKSCSTable",
    "kIBMJapanTable",
    "kIICoreTable",
    "kIRGDaeJaweonTable",
    "kIRGDaiKanwaZitenTable",
    "kIRGHanyuDaZidianTable",
    "kIRGKangXiTable",
    "kJapaneseKunTable",
    "kJapaneseOnTable",
    "kJIS0213Table",
    "kJis0Table",
    "kJis1Table",
    "kKangXiTable",
    "kKarlgrenTable",
    "kKoreanTable",
    "kKPS0Table",
    "kKPS1Table",
    "kKSC0Table",
    "kKSC1Table",
    "kLauTable",
    "kMainlandTelegraphTable",
    "kMandarinTable",
    "kMatthewsTable",
    "kMeyerWempeTable",
    "kMorohashiTable",
    "kNelsonTable",
    "kOtherNumericTable",
    "kPhoneticTable",
    "kPrimaryNumericTable",
    "kPseudoGB1Table",
    "kRSAdobe_Japan1_6Table",
    "kRSJapaneseTable",
    "kRSKangXiTable",
    "kRSKanWaTable",
    "kRSKoreanTable",
    "kRSUnicodeTable",
    "kSBGYTable",
    "kSemanticVariantTable",
    "kSimplifiedVariantTable",
    "kSpecializedSemanticVariantTable",
    "kTaiwanTelegraphTable",
    "kTangTable",
    "kTotalStrokesTable",
    "kTraditionalVariantTable",
    "kVietnameseTable",
    "kXeroxTable",
    "kXHC1983Table",
    "kZVariantTable",

    "utf8Table",

    "IRG_SourceTable",

    "IRG_SourceMappingTable",

    "kSemanticVariantTableExtra",
    "kSpecializedSemanticVariantTableExtra",
    "kZVariantTableExtra",
    NULL
};



/**
 * Fields that holds integer.
 *
 * Note that 0-padded fields (such as UNIHAN_FIELD_ADDITIONAL_STROKE_COUNT) are not treated as integer.
 */
const UnihanField UNIHAN_INTEGER_FIELDS[]={
    UNIHAN_FIELD_CODE,
    UNIHAN_FIELD_kACCOUNTINGNUMERIC,
    UNIHAN_FIELD_kCOMPATIBILITYVARIANT,
    UNIHAN_FIELD_kFREQUENCY,
    UNIHAN_FIELD_kGRADELEVEL,
    UNIHAN_FIELD_kOTHERNUMERIC,
    UNIHAN_FIELD_kPRIMARYNUMERIC,
    UNIHAN_FIELD_kSIMPLIFIEDVARIANT,

    UNIHAN_FIELD_kTOTALSTROKES,
    UNIHAN_FIELD_kTRADITIONALVARIANT,

    UNIHAN_FIELD_VARIANT_CODE,
    UNIHAN_FIELD_SEMANTIC_T,
    UNIHAN_FIELD_SEMANTIC_B,
    UNIHAN_FIELD_SEMANTIC_Z,

    UNIHAN_FIELD_ADOBE_CID_RADICAL_STROKE_COUNT,

    UNIHAN_FIELD_KANGXI_VIRTUAL,
    UNIHAN_FIELD_FREQ_RANK,
    UNIHAN_FIELD_PINYIN_FREQ,
    UNIHAN_INVALID_FIELD
};


UnihanField UNIHAN_IRG_SOURCE_FIELDS[]={
    UNIHAN_FIELD_kIRG_GSOURCE,
    UNIHAN_FIELD_kIRG_HSOURCE,
    UNIHAN_FIELD_kIRG_JSOURCE,
    UNIHAN_FIELD_kIRG_KPSOURCE,
    UNIHAN_FIELD_kIRG_KSOURCE,
    UNIHAN_FIELD_kIRG_TSOURCE,
    UNIHAN_FIELD_kIRG_USOURCE,
    UNIHAN_FIELD_kIRG_VSOURCE,
    UNIHAN_INVALID_FIELD
};

const UnihanField UNIHAN_KRS_FIELDS[]={
    UNIHAN_FIELD_kRSADOBE_JAPAN1_6,
    UNIHAN_FIELD_kRSJAPANESE,
    UNIHAN_FIELD_kRSKANGXI,
    UNIHAN_FIELD_kRSKANWA,
    UNIHAN_FIELD_kRSKOREAN,
    UNIHAN_FIELD_kRSUNICODE,
    UNIHAN_INVALID_FIELD
};

const UnihanField UNIHAN_KVARIANT_FIELDS[]={
    UNIHAN_FIELD_kCOMPATIBILITYVARIANT,
    UNIHAN_FIELD_kSEMANTICVARIANT,
    UNIHAN_FIELD_kSIMPLIFIEDVARIANT,
    UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT, 
    UNIHAN_FIELD_kTRADITIONALVARIANT,
    UNIHAN_FIELD_kZVARIANT,
    UNIHAN_INVALID_FIELD
};


const UnihanField UNIHAN_UCS4_FIELDS[]={
    UNIHAN_FIELD_CODE,
    UNIHAN_FIELD_kCOMPATIBILITYVARIANT,
    UNIHAN_FIELD_kSEMANTICVARIANT,
    UNIHAN_FIELD_kSIMPLIFIEDVARIANT,
    UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT, 
    UNIHAN_FIELD_kTRADITIONALVARIANT,
    UNIHAN_FIELD_kZVARIANT,
    UNIHAN_FIELD_VARIANT_CODE,
    UNIHAN_INVALID_FIELD
};

const UnihanField UNIHAN_MANDARIN_FIELDS[]={
    UNIHAN_FIELD_kMANDARIN,
    UNIHAN_FIELD_PINYIN,
    UNIHAN_FIELD_ZHUYIN,
    UNIHAN_INVALID_FIELD
};

const UnihanField UNIHAN_CASE_NO_CHANGE_FIELDS[]={
    UNIHAN_FIELD_UTF8,
    UNIHAN_FIELD_kCHEUNGBAUER,
    UNIHAN_FIELD_kCHEUNGBAUERINDEX,
    UNIHAN_FIELD_kCIHAIT,
    UNIHAN_FIELD_kCOWLES,
    UNIHAN_FIELD_kDAEJAWEON,
    UNIHAN_FIELD_kDEFINITION,
    UNIHAN_FIELD_kFENNINDEX,
    UNIHAN_FIELD_kFOURCORNERCODE,
    UNIHAN_FIELD_kHANYU,
    UNIHAN_FIELD_kIICORE,
    UNIHAN_FIELD_kIRGDAIKANWAZITEN,
    UNIHAN_FIELD_kIRGKANGXI,
    UNIHAN_FIELD_kJIS0213,
    UNIHAN_FIELD_kJIS0,
    UNIHAN_FIELD_kJIS1,
    UNIHAN_FIELD_kKANGXI,
    UNIHAN_FIELD_kKSC0,
    UNIHAN_FIELD_kKSC1,
    UNIHAN_FIELD_kLAU,
    UNIHAN_FIELD_kMAINLANDTELEGRAPH,
    UNIHAN_FIELD_kMOROHASHI,
    UNIHAN_FIELD_kNELSON,
    UNIHAN_FIELD_kPSEUDOGB1,
    UNIHAN_FIELD_kRSJAPANESE,
    UNIHAN_FIELD_kRSKANGXI,
    UNIHAN_FIELD_kRSKANWA,
    UNIHAN_FIELD_kRSKOREAN,
    UNIHAN_FIELD_kRSUNICODE,
    UNIHAN_FIELD_kSBGY,
    UNIHAN_FIELD_kSEMANTICVARIANT,
    UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT,
    UNIHAN_FIELD_kTAIWANTELEGRAPH,
    UNIHAN_FIELD_kTANG,
    UNIHAN_FIELD_kVIETNAMESE,
    UNIHAN_FIELD_kXEROX,

    UNIHAN_INVALID_FIELD
};


const UnihanField UNIHAN_LOWERCASE_FIELDS[]={
    UNIHAN_FIELD_kCANTONESE,
    UNIHAN_FIELD_kHANYUPINLU,
    UNIHAN_FIELD_kGSR,
    UNIHAN_FIELD_kMATTHEWS,
    UNIHAN_FIELD_kMEYERWEMPE,
    UNIHAN_FIELD_kXHC1983,
    UNIHAN_INVALID_FIELD
};

/**
 * Fields that are functional dependent to code.
 *
 * 
 */
const UnihanField UNIHAN_SINGLETON_FIELDS[]={
    UNIHAN_FIELD_CODE,
    UNIHAN_FIELD_kACCOUNTINGNUMERIC,
    UNIHAN_FIELD_kBIGFIVE,
    UNIHAN_FIELD_kCCCII,
    UNIHAN_FIELD_kCHEUNGBAUER,
    UNIHAN_FIELD_kCNS1986,
    UNIHAN_FIELD_kCNS1992,
    UNIHAN_FIELD_kDEFINITION,
    UNIHAN_FIELD_kFOURCORNERCODE,
    UNIHAN_FIELD_kFREQUENCY,
    UNIHAN_FIELD_kGB0,
    UNIHAN_FIELD_kGB1,
    UNIHAN_FIELD_kGB3,
    UNIHAN_FIELD_kGB5,
    UNIHAN_FIELD_kGB7,
    UNIHAN_FIELD_kGB8,
    UNIHAN_FIELD_kGRADELEVEL,
    UNIHAN_FIELD_kHKSCS,
    UNIHAN_FIELD_kHKGLYPH,
    UNIHAN_FIELD_kIICORE,
    UNIHAN_FIELD_kIBMJAPAN,
    UNIHAN_FIELD_kJIS0213,
    UNIHAN_FIELD_kJIS0,	
    UNIHAN_FIELD_kJIS1,	
    UNIHAN_FIELD_kKPS0,
    UNIHAN_FIELD_kKPS1,
    UNIHAN_FIELD_kKSC0,
    UNIHAN_FIELD_kKSC1,
    UNIHAN_FIELD_kMAINLANDTELEGRAPH,
    UNIHAN_FIELD_kOTHERNUMERIC,
    UNIHAN_FIELD_kPRIMARYNUMERIC,
    UNIHAN_FIELD_kTAIWANTELEGRAPH,
    UNIHAN_FIELD_kTOTALSTROKES,
    UNIHAN_FIELD_kXEROX,
    UNIHAN_FIELD_UTF8,
    UNIHAN_INVALID_FIELD
};

UnihanIRG_SourceData UNIHAN_IRG_SOURCES[]={
    {"G0","GB2312-80"},
    {"G1","GB12345-90 with 58 Hong Kong and 92 Korean \"Idu\" characters"},
    {"G3","GB7589-87 unsimplified forms"},
    {"G5","GB7590-87 unsimplified forms"},
    {"G7","General Purpose Hanzi List for Modern Chinese Language, and General List of Simplified Hanzi"},
    {"GS","Singapore characters"},
    {"G8","GB8685-88"},
    {"GE","GB16500-95"},
    {"G9","GB18030-2000"},
    {"G4K","Siku Quanshu"},
    {"GBK","Chinese Encyclopedia"},
    {"GCH","The Ci Hai (PRC edition)"},
    {"GCY","The Ci Yuan "},
    {"GFZ","Founder Press System"},
    {"GFZ_BK","Founder Press System"},
    {"GHC","The Hanyu Da Cidian"},
    {"GHZ","The Hanyu Da Zidian"},
    {"GKX","The KangXi dictionary"},

    {"H","Hong Kong Supplementary Character Set"},
    {"J0","JIS X 0208:1990"},
    {"J1","JIS X 0212:1990"},
    {"JA","Unified Japanese IT Vendors Contemporary Ideographs, 1993"},
    {"J3","JIS X 0213:2000"},
    {"J3A","JIS X 0213:2004 level-3"},
    {"J4","JIS X 0213:2000"},

    {"KP0","KPS 9566-97"},
    {"KP1","KPS 10721-2000"},

    {"K0","KS C 5601-1987"},
    {"K1","KS C 5657-1991"},
    {"K2","PKS C 5700-1 1994"},
    {"K3","PKS C 5700-2 1994"},
    {"K4","PKS 5700-3:1998"},

    {"T1","CNS 11643-1992, plane 1"},
    {"T2","CNS 11643-1992, plane 2"},
    {"T3","CNS 11643-1992, plane 3 (with some additional characters)"},
    {"T4","CNS 11643-1992, plane 4"},
    {"T5","CNS 11643-1992, plane 5"},
    {"T6","CNS 11643-1992, plane 6"},
    {"T7","CNS 11643-1992, plane 7"},
    {"TF","CNS 11643-1992, plane 15"},

    {"U","Other sources which were used by the Unicode Consortium"},

    {"V0","TCVN 5773:1993"},
    {"V1","TCVN 6056:1995"},
    {"V2","VHN 01:1998"},
    {"V3","VHN 02:1998"},
    {NULL}
};

#define UNIHAN_NOINDEX_IRG_SOURCES_COUNT	9
const UnihanIRG_SourceId UNIHAN_NOINDEX_IRG_SOURCES[UNIHAN_NOINDEX_IRG_SOURCES_COUNT]={
    UNIHAN_SOURCE_G4K,
    UNIHAN_SOURCE_GBK,
    UNIHAN_SOURCE_GCH,
    UNIHAN_SOURCE_GCY,
    UNIHAN_SOURCE_GFZ,
    UNIHAN_SOURCE_GFZ_BK,
    UNIHAN_SOURCE_GHC,
    UNIHAN_SOURCE_GHZ,
    UNIHAN_SOURCE_GKX
};

const char UNIHAN_LOCALE_NAMES[UNIHAN_LOCALES_COUNT][6]={
    "ja_JP",  
    "ko_KP",  
    "ko_KR",
    "zh_CN",  
    "zh_HK",  
    "zh_SG",  
    "zh_TW",  
    "vi_VN",
};

const char *UNIHAN_RANGE_NAMES[UNIHAN_RANGES_COUNT]={
    "CJK Unified Ideographs Extension A",
    "CJK Unified Ideographs",
    "CJK Unified Ideographs (4.1)",
    "CJK Unified Ideographs (5.1)",
    "CJK Compatibility Ideographs (a)",
    "CJK Compatibility Ideographs (b)",
    "CJK Compatibility Ideographs (4.1)",
    "CJK Unified Ideographs Extension B",
    "CJK Compatibility Supplement"
};


const UnihanFieldTablePair PSEUDO_FIELDS_REQUIRED_TABLES[]={
    {UNIHAN_FIELD_kIRG_GSOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_GSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_HSOURCE,  UNIHAN_TABLE_IRG_SOURCE}, 
    {UNIHAN_FIELD_kIRG_HSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING}, 
    {UNIHAN_FIELD_kIRG_JSOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_JSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_KPSOURCE, UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_KPSOURCE, UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_KSOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_KSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_TSOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_TSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_USOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_USOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kIRG_VSOURCE,  UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_VSOURCE,  UNIHAN_TABLE_IRG_SOURCE_MAPPING},
    {UNIHAN_FIELD_kSEMANTICVARIANT, UNIHAN_TABLE_kSEMANTICVARIANT},
    {UNIHAN_FIELD_kSEMANTICVARIANT, UNIHAN_TABLE_kSEMANTICVARIANT_EXTRA},
    {UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT,  UNIHAN_TABLE_kSPECIALIZEDSEMANTICVARIANT},
    {UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT,  UNIHAN_TABLE_kSPECIALIZEDSEMANTICVARIANT_EXTRA},
    {UNIHAN_FIELD_kZVARIANT, UNIHAN_TABLE_kZVARIANT},
    {UNIHAN_FIELD_kZVARIANT, UNIHAN_TABLE_kZVARIANT_EXTRA},
    {UNIHAN_FIELD_kRSADOBE_JAPAN1_6, UNIHAN_TABLE_kRSADOBE_JAPAN1_6},
    {UNIHAN_FIELD_kRSJAPANESE, UNIHAN_TABLE_kRSJAPANESE},
    {UNIHAN_FIELD_kRSKANGXI, UNIHAN_TABLE_kRSKANGXI},
    {UNIHAN_FIELD_kRSKANWA, UNIHAN_TABLE_kRSKANWA},
    {UNIHAN_FIELD_kRSKOREAN, UNIHAN_TABLE_kRSKOREAN},
    {UNIHAN_FIELD_kRSUNICODE, UNIHAN_TABLE_kRSUNICODE},
    {UNIHAN_FIELD_kHANYUPINLU, UNIHAN_TABLE_kHANYUPINLU},
    {UNIHAN_FIELD_kIRGKANGXI, UNIHAN_TABLE_kIRGKANGXI},
    {UNIHAN_FIELD_kKANGXI, UNIHAN_TABLE_kKANGXI},
    {UNIHAN_FIELD_ZHUYIN,  UNIHAN_TABLE_kMANDARIN},
    {UNIHAN_FIELD_UTF8,    UNIHAN_TABLE_CODE},
    {UNIHAN_INVALID_FIELD,  UNIHAN_INVALID_TABLE},
};

const UnihanFieldTablePair FIELD_PREFERRED_TABLES[]={
    {UNIHAN_FIELD_CODE,			UNIHAN_TABLE_CODE},
    {UNIHAN_FIELD_kACCOUNTINGNUMERIC,	UNIHAN_TABLE_kACCOUNTINGNUMERIC},
    {UNIHAN_FIELD_kBIGFIVE,		UNIHAN_TABLE_kBIGFIVE},
    {UNIHAN_FIELD_kCANGJIE,		UNIHAN_TABLE_kCANGJIE},
    {UNIHAN_FIELD_kCANTONESE,		UNIHAN_TABLE_kCANTONESE},
    {UNIHAN_FIELD_kCCCII,		UNIHAN_TABLE_kCCCII},
    {UNIHAN_FIELD_kCHEUNGBAUER,		UNIHAN_TABLE_kCHEUNGBAUER},
    {UNIHAN_FIELD_kCHEUNGBAUERINDEX,	UNIHAN_TABLE_kCHEUNGBAUERINDEX},
    {UNIHAN_FIELD_kCIHAIT,		UNIHAN_TABLE_kCIHAIT},
    {UNIHAN_FIELD_kCNS1986,		UNIHAN_TABLE_kCNS1986},
    {UNIHAN_FIELD_kCNS1992,		UNIHAN_TABLE_kCNS1992},
    {UNIHAN_FIELD_kCOMPATIBILITYVARIANT,		UNIHAN_TABLE_kCOMPATIBILITYVARIANT},
    {UNIHAN_FIELD_kCOWLES,		UNIHAN_TABLE_kCOWLES},
    {UNIHAN_FIELD_kDAEJAWEON,		UNIHAN_TABLE_kDAEJAWEON},
    {UNIHAN_FIELD_kDEFINITION,		UNIHAN_TABLE_kDEFINITION},
    {UNIHAN_FIELD_kEACC,		UNIHAN_TABLE_kEACC},
    {UNIHAN_FIELD_kFENN,		UNIHAN_TABLE_kFENN},
    {UNIHAN_FIELD_kFENNINDEX,		UNIHAN_TABLE_kFENNINDEX},
    {UNIHAN_FIELD_kFOURCORNERCODE,	UNIHAN_TABLE_kFOURCORNERCODE},
    {UNIHAN_FIELD_kFREQUENCY,		UNIHAN_TABLE_kFREQUENCY},
    {UNIHAN_FIELD_kGB0,			UNIHAN_TABLE_kGB0},
    {UNIHAN_FIELD_kGB1,			UNIHAN_TABLE_kGB1},
    {UNIHAN_FIELD_kGB3,			UNIHAN_TABLE_kGB3},
    {UNIHAN_FIELD_kGB5,			UNIHAN_TABLE_kGB5},
    {UNIHAN_FIELD_kGB7,			UNIHAN_TABLE_kGB7},
    {UNIHAN_FIELD_kGB8,			UNIHAN_TABLE_kGB8},
    {UNIHAN_FIELD_kGRADELEVEL,		UNIHAN_TABLE_kGRADELEVEL},
    {UNIHAN_FIELD_kGSR,			UNIHAN_TABLE_kGSR},
    {UNIHAN_FIELD_kHANGUL,		UNIHAN_TABLE_kHANGUL},
    {UNIHAN_FIELD_kHANYU,		UNIHAN_TABLE_kHANYU},
    {UNIHAN_FIELD_kHANYUPINLU,		UNIHAN_TABLE_kHANYUPINLU},
    {UNIHAN_FIELD_kHDZRADBREAK,		UNIHAN_TABLE_kHDZRADBREAK},
    {UNIHAN_FIELD_kHKGLYPH,		UNIHAN_TABLE_kHKGLYPH},
    {UNIHAN_FIELD_kHKSCS,		UNIHAN_TABLE_kHKSCS},
    {UNIHAN_FIELD_kIBMJAPAN,		UNIHAN_TABLE_kIBMJAPAN},
    {UNIHAN_FIELD_kIICORE,		UNIHAN_TABLE_kIICORE},
    {UNIHAN_FIELD_kIRGDAEJAWEON,	UNIHAN_TABLE_kIRGDAEJAWEON},
    {UNIHAN_FIELD_kIRGDAIKANWAZITEN,	UNIHAN_TABLE_kIRGDAIKANWAZITEN},
    {UNIHAN_FIELD_kIRGHANYUDAZIDIAN,	UNIHAN_TABLE_kIRGHANYUDAZIDIAN},
    {UNIHAN_FIELD_kIRGKANGXI,		UNIHAN_TABLE_kIRGKANGXI},
    {UNIHAN_FIELD_kIRG_GSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_HSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_JSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_KPSOURCE,	UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_KSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_TSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_USOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kIRG_VSOURCE,		UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_kJAPANESEKUN,		UNIHAN_TABLE_kJAPANESEKUN},
    {UNIHAN_FIELD_kJAPANESEON,		UNIHAN_TABLE_kJAPANESEON},
    {UNIHAN_FIELD_kJIS0213,		UNIHAN_TABLE_kJIS0213},
    {UNIHAN_FIELD_kJIS0,		UNIHAN_TABLE_kJIS0},
    {UNIHAN_FIELD_kJIS1,		UNIHAN_TABLE_kJIS1},
    {UNIHAN_FIELD_kKANGXI,		UNIHAN_TABLE_kKANGXI},
    {UNIHAN_FIELD_kKARLGREN,		UNIHAN_TABLE_kKARLGREN},
    {UNIHAN_FIELD_kKOREAN,		UNIHAN_TABLE_kKOREAN},
    {UNIHAN_FIELD_kKPS0,		UNIHAN_TABLE_kKPS0},
    {UNIHAN_FIELD_kKPS1,		UNIHAN_TABLE_kKPS1},
    {UNIHAN_FIELD_kKSC0,		UNIHAN_TABLE_kKSC0},
    {UNIHAN_FIELD_kKSC1,		UNIHAN_TABLE_kKSC1},
    {UNIHAN_FIELD_kLAU,			UNIHAN_TABLE_kLAU},
    {UNIHAN_FIELD_kMAINLANDTELEGRAPH,	UNIHAN_TABLE_kMAINLANDTELEGRAPH},
    {UNIHAN_FIELD_kMANDARIN,		UNIHAN_TABLE_kMANDARIN},
    {UNIHAN_FIELD_kMATTHEWS,		UNIHAN_TABLE_kMATTHEWS},
    {UNIHAN_FIELD_kMEYERWEMPE,		UNIHAN_TABLE_kMEYERWEMPE},
    {UNIHAN_FIELD_kMOROHASHI,		UNIHAN_TABLE_kMOROHASHI},
    {UNIHAN_FIELD_kNELSON,		UNIHAN_TABLE_kNELSON},
    {UNIHAN_FIELD_kOTHERNUMERIC,	UNIHAN_TABLE_kOTHERNUMERIC},
    {UNIHAN_FIELD_kPHONETIC,		UNIHAN_TABLE_kPHONETIC},
    {UNIHAN_FIELD_kPRIMARYNUMERIC,	UNIHAN_TABLE_kPRIMARYNUMERIC},
    {UNIHAN_FIELD_kPSEUDOGB1,		UNIHAN_TABLE_kPSEUDOGB1},
    {UNIHAN_FIELD_kRSADOBE_JAPAN1_6,	UNIHAN_TABLE_kRSADOBE_JAPAN1_6},
    {UNIHAN_FIELD_kRSJAPANESE,		UNIHAN_TABLE_kRSJAPANESE},
    {UNIHAN_FIELD_kRSKANGXI,		UNIHAN_TABLE_kRSKANGXI},
    {UNIHAN_FIELD_kRSKANWA,		UNIHAN_TABLE_kRSKANWA},
    {UNIHAN_FIELD_kRSKOREAN,		UNIHAN_TABLE_kRSKOREAN},
    {UNIHAN_FIELD_kRSUNICODE,		UNIHAN_TABLE_kRSUNICODE},
    {UNIHAN_FIELD_kSBGY,		UNIHAN_TABLE_kSBGY},
    {UNIHAN_FIELD_kSEMANTICVARIANT,	UNIHAN_TABLE_kSEMANTICVARIANT},
    {UNIHAN_FIELD_kSIMPLIFIEDVARIANT,	UNIHAN_TABLE_kSIMPLIFIEDVARIANT},
    {UNIHAN_FIELD_kSPECIALIZEDSEMANTICVARIANT,		UNIHAN_TABLE_kSPECIALIZEDSEMANTICVARIANT},
    {UNIHAN_FIELD_kTAIWANTELEGRAPH,	UNIHAN_TABLE_kTAIWANTELEGRAPH},
    {UNIHAN_FIELD_kTANG,		UNIHAN_TABLE_kTANG},
    {UNIHAN_FIELD_kTOTALSTROKES,	UNIHAN_TABLE_kTOTALSTROKES},
    {UNIHAN_FIELD_kTRADITIONALVARIANT,	UNIHAN_TABLE_kTRADITIONALVARIANT},
    {UNIHAN_FIELD_kVIETNAMESE,		UNIHAN_TABLE_kVIETNAMESE},
    {UNIHAN_FIELD_kXEROX,		UNIHAN_TABLE_kXEROX},
    {UNIHAN_FIELD_kXHC1983,		UNIHAN_TABLE_kXHC1983},
    {UNIHAN_FIELD_kZVARIANT,		UNIHAN_TABLE_kZVARIANT},

    {UNIHAN_FIELD_UTF8,			UNIHAN_TABLE_CODE},

    {UNIHAN_FIELD_IRG_SOURCE_SHORT_NAME,	UNIHAN_TABLE_IRG_SOURCE},
    {UNIHAN_FIELD_IRG_SOURCE_MAPPING,		UNIHAN_TABLE_IRG_SOURCE_MAPPING},

    {UNIHAN_FIELD_VARIANT_CODE,		UNIHAN_TABLE_kSEMANTICVARIANT},

    {UNIHAN_FIELD_FROM_DICT,		UNIHAN_TABLE_kSEMANTICVARIANT_EXTRA},
    {UNIHAN_FIELD_SEMANTIC_T,		UNIHAN_TABLE_kSEMANTICVARIANT_EXTRA},
    {UNIHAN_FIELD_SEMANTIC_B,		UNIHAN_TABLE_kSEMANTICVARIANT_EXTRA},
    {UNIHAN_FIELD_SEMANTIC_Z,		UNIHAN_TABLE_kSEMANTICVARIANT_EXTRA},

    {UNIHAN_FIELD_RADICAL_INDEX,		UNIHAN_TABLE_kRSUNICODE},
    {UNIHAN_FIELD_ADDITIONAL_STROKE_COUNT,	UNIHAN_TABLE_kRSUNICODE},
    {UNIHAN_FIELD_RADICAL_IS_SIMPLIFIED,	UNIHAN_TABLE_kRSUNICODE},

    {UNIHAN_FIELD_ADOBE_CID_CV,		UNIHAN_TABLE_kRSADOBE_JAPAN1_6},
    {UNIHAN_FIELD_ADOBE_CID,		UNIHAN_TABLE_kRSADOBE_JAPAN1_6},
    {UNIHAN_FIELD_ADOBE_CID_RADICAL_STROKE_COUNT,	UNIHAN_TABLE_kRSADOBE_JAPAN1_6},

    {UNIHAN_FIELD_KANGXI_PAGE,		UNIHAN_TABLE_kKANGXI},
    {UNIHAN_FIELD_KANGXI_CHARNUM,	UNIHAN_TABLE_kKANGXI},
    {UNIHAN_FIELD_KANGXI_VIRTUAL,	UNIHAN_TABLE_kKANGXI},

    {UNIHAN_FIELD_FREQ_RANK,		UNIHAN_TABLE_kMANDARIN},

    {UNIHAN_FIELD_PINYIN,		UNIHAN_TABLE_kMANDARIN},
    {UNIHAN_FIELD_PINYIN_BASE,		UNIHAN_TABLE_kMANDARIN},
    {UNIHAN_FIELD_PINYIN_TONE,		UNIHAN_TABLE_kMANDARIN},
    {UNIHAN_FIELD_PINYIN_FREQ,		UNIHAN_TABLE_kHANYUPINLU},

    {UNIHAN_FIELD_ZVARIANT_SOURCE,	UNIHAN_TABLE_kZVARIANT},

    {UNIHAN_FIELD_ZHUYIN,		UNIHAN_TABLE_kMANDARIN},

    {UNIHAN_INVALID_FIELD,  UNIHAN_INVALID_TABLE},
};

